name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull lokeshhs591/nodejsapp:latest
      - name: Delete old container
        run: sudo docker rm -f nodejsapp
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name nodejsapp lokeshhs591/nodejsapp